feat: Spring Security 추가
ppp-team/my-petlog-server pull request #7
Opened 2024-01-29 08:10 UTC by llsrrll96

## 🔎 PR Description
- Close #5 
> Spring Security 추가

## 🔑 Key Changes
- Spring Security 추가
- 회원가입, 로그인 인증관련 기능 추가

## 📢 To Reviewers
- 시큐리티와 회원가입, 로그인도 추가했습니다.

2024-01-29 09:37 UTC, thdefn requested changes
https://velog.io/@haden/스프링-7-Spring-Security와-JWT

이건 도움되실만한 블로그 자료입니다. Security  버전이 5이지만 플로우 이해하시는데 한번 살펴보시면 좋을 것 같아요!

2024-01-29 11:45 UTC, llsrrll96 commented
네 감사해요! 수정중 (땀땀)

2024-01-29 14:06 UTC, thdefn commented on petlog-api/src/main/java/com/ppp/api/auth/exception/SigninException.java
> +public class SigninException extends RuntimeException{
모든 api에 대한 익셉션 클래스를 만드는 것보다는 `AuthException` 으로 가는 게 어떨까요 ?

2024-01-29 14:06 UTC, thdefn commented on petlog-api/src/main/java/com/ppp/api/auth/exception/UserExceptionHandler.java
> +@RestControllerAdvice(basePackages = {"com.ppp.api.auth", "com.ppp.api.user"})
`GlobalExceptionHandler` 를 만들어두셨는데 도메인익셉션 클래스를 따로 만드신 이유가 궁금합니다

2024-01-29 14:06 UTC, thdefn commented on petlog-common/src/main/java/com/ppp/common/security/PrincipalDetails.java
> +    private Set<GrantedAuthority> grantedAuthorities;
이 부분 왜 Set 자료구조를 선택하셨는지 궁금합니다 !

2024-01-29 14:06 UTC, thdefn commented on petlog-api/src/main/java/com/ppp/api/auth/controller/AuthController.java
> +        if (refreshToken == null) throw new TokenException(ErrorCode.NOT_FOUND_TOKEN);
`@RequestHeader(required = true)` 가 디폴트이기 때문에, null 체크는 제외해도 좋을 것 같습니다

2024-01-29 14:06 UTC, thdefn commented on petlog-api/src/main/java/com/ppp/api/auth/controller/AuthController.java
> +            ApiResponse<User> failResponse = ApiResponse.fail("fail", "회원가입에 실패했습니다!");
이 부분 왜 throw 로 Error 를 던지지않고 `ApiResponse` 를 생성하셨는지 궁금합니다. `ApiResponse` 와 `ErrorResponse` 가 함께 있으니까 조금은 코드를 이해하기 어려워질수도 있을 것 같아요.

2024-01-29 14:39 UTC, thdefn commented on petlog-api/src/main/java/com/ppp/api/auth/controller/AuthController.java
> +        if(user == null) {
서비스 코드를 살펴보니 null을 리턴할 상황은 없어보입니다. 혹시 어떤 부분에서 null 체크 코드를 작성하신걸까요?

2024-01-29 18:22 UTC, thdefn requested changes

2024-01-29 18:22 UTC, thdefn commented on petlog-api/src/main/java/com/ppp/api/auth/controller/AuthController.java
> +     * 회원가입
Clean Code 에 따르면 주석은 유지보수성이 떨어지고 일명 레거시 코드를 생산합니다. 주석은 todo 제외하고는 삭제하시고 최대한 코드 레벨에서 의도를 표현해주세요.

https://github.com/taeiim/CleanCode-Study/blob/master/Clean%20Code/Clean%20Code%204%EC%9E%A5.%20%EC%A3%BC%EC%84%9D.md

2024-01-29 18:56 UTC, thdefn commented on petlog-api/src/main/java/com/ppp/api/auth/controller/AuthController.java
> +        jwtTokenProvider.validateRefreshToken(refreshToken, request);
검증은 서비스에 들어가야할것같아요

2024-01-29 19:15 UTC, thdefn requested changes

2024-01-29 19:15 UTC, thdefn commented on petlog-common/src/main/java/com/ppp/common/security/CustomUserDetailsService.java
> +    final UserRepository memberRepository;
필드명 엔티티에 맞게 수정 요청드리며 클래스명도 CustomUserDetailsService 보다는 UserDetailsServiceImpl 같이 직관적인게 어떨까요?

2024-01-29 19:21 UTC, thdefn requested changes

2024-01-29 19:21 UTC, thdefn commented on petlog-api/src/main/java/com/ppp/api/user/dto/SigninDto.java
> +public class SigninDto {
`-Request` 컨벤션 지켜주세요

2024-01-30 05:56 UTC, llsrrll96 commented on petlog-api/src/main/java/com/ppp/api/auth/exception/UserExceptionHandler.java
> +@RestControllerAdvice(basePackages = {"com.ppp.api.auth", "com.ppp.api.user"})
GlobalExceptionHandler 1개로 통합

2024-01-30 05:57 UTC, llsrrll96 commented on petlog-common/src/main/java/com/ppp/common/security/PrincipalDetails.java
> +    private Set<GrantedAuthority> grantedAuthorities;
권한 담는 용도이지만 삭제했습니다.

2024-01-30 05:57 UTC, llsrrll96 commented on petlog-api/src/main/java/com/ppp/api/auth/controller/AuthController.java
> +        jwtTokenProvider.validateRefreshToken(refreshToken, request);
수정했습니다.

2024-01-30 06:35 UTC, thdefn commented on petlog-common/src/main/java/com/ppp/common/security/PrincipalDetails.java
> +    private Set<GrantedAuthority> grantedAuthorities;
엇 그저 Collections 중 Set을 선택하신 이유가 궁금해서 여쭤봤습니다 ! List를 쓰시는 경우는 많이 봤는데, Set을 쓰면 조회가 더 빠르니까 그 부분에서 채택하신건가 싶어서요. 권한은 Collections 중 하나에 담아두는 것이 좋을 것 같습니다.

2024-01-30 06:37 UTC, thdefn approved these changes

2024-01-30 08:55 UTC, merged